### ISSUE TITLE
package.json references private git repo

### ISSUE THREAD

**Issue by modille** [upmc-enterprises/captain-whisker#1]
https://github.com/upmc-enterprises/captain-whisker/blob/f1f9383a26994fb76247e7db6b96945c07ce184b/package.json#L13 seems to reference a private git repo.

I don't think it actually matters, since https://www.npmjs.com/package/captain-whisker has a `repository` link that goes to GitHub, but just a heads up.

**Comment by jreiter** [comment]
Yeah, I noticed that yesterday.  Pushed up a fix today.  Thanks!
